[package]
name = "snake-rs"
version = "0.1.0"
authors = ["Pierre Chevalier <pierrechevalier83@gmail.com>"]

[dependencies]
"num" = "0.1"
"matrix_display" = "0.5"
"rand" = "0.3"
"termion" = "1.3"
"tui" = "0.1"
